# Defines stages which are to be executed
stages:
  - APPS_CXX_Build_and_Test

# Build with NVHPC compiler
build:NVHCP23:API_CXX:
  stage: APPS_CXX_Build_and_Test
  tags:
    - CCP, test
  script:
    - source ~/.bash_aliases
    - module avail 
    - module load nvhpc/23.9
    - export CXX=mpicxx
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/OPS-INSTALL -DBUILD_OPS_APPS=ON -DAPP_INSTALL_DIR=$CI_PROJECT_DIR/OPS-APP -DOPS_TEST=ON -DGPU_ARCH=75 -DGPU_NUMBER=1
    - cmake --build . -j 4
    - cmake --install . 
    - ctest -V
  artifacts:
    expire_in: 1 week
    paths:
    - $CI_PROJECT_DIR/OPS-APP
