# Auroraflow

CALLING_MAKEFILE_PATH := $(abspath $(firstword $(MAKEFILE_LIST)))
CALLING_MAKEFILE_DIR  := $(dir $(CALLING_MAKEFILE_PATH))

AURORA_FLOW_BUILD_DIR=$(CALLING_MAKEFILE_DIR)/hls/build/$(HLS_TARGET_MODE)/aurora_flow/
AURORA_FLOW_PIPE_DIR?=$(CALLING_MAKEFILE_DIR)/hls/build/$(HLS_TARGET_MODE)/aurora_pipe/
AURORA_NUM_RANK?=2

ifdef AURORA_FLOW_INSTALL_PATH
AURORA_FLOW_DIR := $(AURORA_FLOW_INSTALL_PATH)
include $(AURORA_FLOW_DIR)/aurora_flow.mk
endif

HLS_CXXFLAGS+= $(AURORA_FLOW_INCLUDE) -DDATA_WIDTH_BYTES=$(FIFO_WIDTH)
HLS_LDFLAGS  += -L$(XILINX_XRT)/lib -lxrt_coreutil -luuid -lmpi -lops_mpi -lops_hls_mpi -lpthread
